### ISSUE TITLE
Month/Week Change

### ISSUE THREAD

**Issue by RockinGarg** [zjfjack/JZCalendarWeekView#51] opened 2019-03-23 08:37 UTC
How can I be notified that week/Month has been changed
I am fetching 2 month data from backend services 
now I want to be notified when user had switched to third month

Using JZLongPressWeekView
Installed Pods

**Comment by zjfjack** [comment] 2019-03-24 05:25
There is a delegate method from `JZBaseViewDelegate` called `initDateDidChange`.

You can simply refer to the code [DefaultViewController](https://github.com/zjfjack/JZCalendarWeekView/blob/master/Example/JZCalendarWeekViewExample/Source/DefaultViewController.swift) line 62.

**Comment by RockinGarg** [comment] 2019-04-01 16:19
I only used JZLongPressWeekView 
Assigning this protocol "JZBaseViewDelegate"  didn't Called the init Date method

**Comment by RockinGarg** [comment] 2019-04-01 16:20
Actually I need Scrolling Direction so, based on which comparing dates I can request my backend server for required slots to show

**Comment by RockinGarg** [comment] 2019-04-01 16:55
Thanks Got To Know From Your Demo Code

**Comment by RockinGarg** [comment] 2019-04-11 05:34
As you mentioned to use initDateChange Function, I did same 
but resulted in a strange issue
on Some devices like iPhone XS Max, iPhone X InitDate Change function is skipped to call

Please find attached Video - https://drive.google.com/open?id=14upTzeJ6qX8SPrRUbph0YQye2WFZBz-z

I showed toast as soon as InitDataChage function is called
As you could see sometime toast don't show up bcz that function is failed to call.

Can you please suggest Solution what I can do to get it solved?
Thanks

**Comment by RockinGarg** [comment] 2019-04-11 15:57
Hey @zjfjack Any Response. Please

**Comment by zjfjack** [comment] 2019-04-14 10:49
It seems that there are some issues with the pagination, I will look into it soon. If I cannot reproduce it, I will let you know ASAP.

**Comment by RockinGarg** [comment] 2019-04-14 11:11
Thanks this will really help me out. It get stuck on some deices as I mentioned like iPhone XS Max, iPhone X whereas it works perfectly on iPhone 6s. Have a look into it.

**Comment by zjfjack** [comment] 2019-04-14 11:14
I might find the issue which is a quite annoying issue related to some other issues #46 
I will try to fix it, but you have to wait until next weekend.

**Comment by zjfjack** [comment] 2019-05-26 07:09
Hey, mate.

I finally resolve this issue with 0.7.0 version released. It is actually a quite major and difficult problem for the pagination.

You can check the release comment here.

If you have any other issue, let me know. I will close this issue.

Thanks

**Closed by zjfjack** 2019-05-26 07:09 UTC
