### ISSUE TITLE
Calendar events are overlapping

### ISSUE THREAD

**Issue by yashlangaliya** [zjfjack/JZCalendarWeekView#52] opened 2019-04-02 10:12 UTC
Hello, 
First of all, thank you for creating this very useful project.
I'm facing events overlapping due to the wrong cell width calculation.

Check below screenshot, the event's width should scale up to the next event.
![Simulator Screen Shot - iPad Pro (9 7-inch) - 2019-04-02 at 15 04 18](https://user-images.githubusercontent.com/35101358/55393543-15583d00-555b-11e9-8043-44872511cefa.png)

Check below screenshot for overlapping event.
![Simulator Screen Shot - iPad Pro (9 7-inch) - 2019-04-02 at 15 04 49](https://user-images.githubusercontent.com/35101358/55394080-189ff880-555c-11e9-9f3d-5dc98a8e33c4.png)

I tried to find the cause in the flowlayout file. The issue is due to width calculation logic. Currently, it is calculating width by finding all events that intersect new event and then divide the width by the count of overlapping events. which will work great only until all the events have the same duration.

**Comment by zjfjack** [comment] 2019-04-02 12:43
Okay, this seems to be an existing issue, because I found this problem before as well.

However, I didn't find the reason. Could you help me to fix it together? I think you did find some reasons. This calculation logic is actually done by the other project, which means even for me, I am not clear about it.

I will try to do some work to figure out this issue as well. If you can give me more details, then it will be better.

Thanks

**Comment by yashlangaliya** [comment] 2019-04-04 04:50
Hi, Okay so will tell you what is happening in the flowlayout file
- when a new event is added first its location and hight are calculated depending on time and a default width(which is the section width) is given.
- after that, the new event is checked against all the events for overlapping frames.
- after that, a division variable is calculated which is mostly count of overlapping items.
-and then the event width is calculated by `sectionWidth/division`.
 
all this calculation is written in `adjustItemsForOverlap` method.

**Comment by zjfjack** [comment] 2019-04-27 13:11
Hi, Sorry about the late update.

@btxsqdr helped me to find the layout issue solution in #54 #65, could you help me to check whether it also works on your case?

Thanks

**Comment by zjfjack** [comment] 2019-04-28 11:49
Hi, I've improved the overlapping calculation method, could you have a try first?

If the problem still exists, then it means the following method exists bugs as well. I only changed the first part of `adjustItemsForOverlap` method.

Thanks

**Comment by yashlangaliya** [comment] 2019-04-29 03:13
sure, I'll test and let you know.

**Comment by yashlangaliya** [comment] 2019-05-01 09:05
The issue is not solved. 
![Simulator Screen Shot - iPhone 6s - 2019-05-01 at 14 33 34](https://user-images.githubusercontent.com/35101358/57011223-4ab97e80-6c1e-11e9-8d29-e51b3b6de548.png)

**Comment by zjfjack** [comment] 2019-05-01 09:47
Okay, I will look into it this weekend.

Thanks

**Comment by zjfjack** [comment] 2019-05-04 13:10
Hi,

Are you sure that you are using the latest 0.6.3 version? 
I've tried your case, which seems no problem. I will show you the screenshot and code below.

![Simulator Screen Shot - iPhone 8 - 2019-05-04 at 23 07 32](https://user-images.githubusercontent.com/4811838/57179479-ac4d4780-6ec1-11e9-951d-249a6972ad80.png)

```Swift

class AllDayViewModel: NSObject {
    
    private lazy var firstDate = self.dateFormatter.date(from: "2019-05-05 01:15:00")!
    private lazy var secondDate = self.dateFormatter.date(from: "2019-05-05 01:30:00")!
    private lazy var thirdDate = self.dateFormatter.date(from: "2019-05-05 02:45:00")!
    private lazy var fourthDate = self.dateFormatter.date(from: "2019-05-05 04:00:00")!
    private lazy var fifthDate = self.dateFormatter.date(from: "2019-05-05 07:30:00")!
    
    lazy var events = [AllDayEvent(id: "0", title: "One", startDate: firstDate, endDate: firstDate.add(component: .hour, value: 2), location: "Melbourne", isAllDay: false),
                       AllDayEvent(id: "1", title: "Two", startDate: secondDate, endDate: secondDate.add(component: .hour, value: 2), location: "Melbourne", isAllDay: false),
                       AllDayEvent(id: "2", title: "Three", startDate: thirdDate, endDate: thirdDate.add(component: .hour, value: 2), location: "Melbourne", isAllDay: false),
                       AllDayEvent(id: "3", title: "Four", startDate: fourthDate, endDate: fourthDate.add(component: .hour, value: 2), location: "Melbourne", isAllDay: false),
                       AllDayEvent(id: "4", title: "Five", startDate: fifthDate, endDate: fifthDate.add(component: .hour, value: 2), location: "Melbourne", isAllDay: false)]
    
    let dateFormatter: DateFormatter = {
        let dateFormatter = DateFormatter()
        dateFormatter.dateFormat = "yyyy-MM-dd HH:mm:ss"
        dateFormatter.locale = Locale.current
        dateFormatter.timeZone = Calendar.current.timeZone
        return dateFormatter
    }()
    
    lazy var eventsByDate = JZWeekViewHelper.getIntraEventsByDate(originalEvents: events)
    
    var currentSelectedData: OptionsSelectedData!
}

````

Could you check it and let me know? Thanks

**Comment by zjfjack** [comment] 2019-05-04 13:31
Sorry I didn't realise that the order of the events will also influence the layout. Just ignore the previous comment. I will look into the method itself now. I was reproducing your case.

**Comment by zjfjack** [comment] 2019-05-06 15:57
Hi, I've created a new branch [fix-overlapItems](https://github.com/zjfjack/JZCalendarWeekView/tree/fix-overlapItems). 

It can definitely resolve your issue but still exist some issues in some very complicated cases.

Could you test it first and let me know? 

I will try to improve it and add more comments, but to be honest, it is extremely complex (Only Outlook supports this, Apple Calendar and Google Calendar don't support it) and took me more than 10 hours' work.

Thanks

**Comment by zjfjack** [comment] 2019-05-10 03:36
@yashlangaliya hi, Have you checked this code?

**Comment by nobre84** [comment] 2019-07-25 00:17
This is definitely an improvement! Much of my issues are no longer after using the new adjustment code in the fix-overlapItems branch. 👍

**Comment by zjfjack** [comment] 2019-08-18 05:17
Merged. 

There are still some issues existing. I put this in the code. If I have time in the future, I will fix them thanks.

Close it.

**Closed by zjfjack** 2019-08-18 05:17 UTC
